### PR TITLE
Ensure page translation CPs are initialized

### LINKED ISSUE #9383: Investigate .RenderString regression
See https://discourse.gohugo.io/t/multilingual-related-page-renderstring-regression-in-0-92/36555/16?u=bep

I'm pretty sure this came from https://github.com/gohugoio/hugo/pull/9342 -- but I'm also pretty sure that that PR surfaced an already existing bug re output formats and `.Translations`, so I think we need to understand and fix the real issue rather than reverting the above.

@ptgott

### PR DESCRIPTION
**Pull request by ptgott**
PR #9342 introduced a regression in which calling .Translations in a
template and calling RenderString on a translated Page caused a nil
pointer dereference. The issue was that some Pages returned from
.Translations had a nil cp field at the time the calling template was
being executed.

While PR #9342 had attempted to ensure that all ContentProviders were
initialized for translations at build time, it only performed the
initialization for receivers of ContentProvider methods such as
.Summary. However, the ContentProvider's *pageState.pageOutput.cp would
remain uninitialized, causing the nil pointer dereference.

This change edits the .Translations and .AllTranslations methods to
ensure that all of a page's translations have an initialized
content provider in time for a template to be executed.

Since LazyContentProvider is no longer needed with this approach, this
change also reverts the following commits:

- cdcd15b6c2abbb76fd95fbbf90365c56e82f46aa
- 25d645f47ae0a32470d303c9478c9e0b2fff0f0e

Fixes #9383

### CODE REVIEW

File: hugolib/page.go [hunk 1]
```diff
@@ -369,12 +369,50 @@ func (p *pageState) TranslationKey() string {
...
+
+	// Hugo attempts to reuse content providers while preparing each page for
+	// rendering. This approach means that sometimes, content providers for
+	// translations are not initialized. If needed, initialize them here.
+	for _, tr := range p.translations {
+		tp, ok := tr.(*pageState)
+		if !ok {
+			continue
+		}
+		if tp.pageOutput.cp == nil {
```
Comment (bep) [inline hugolib/page.go:406]: Thanks for this.

But I don't think we can solve this like this. Most notably is the data race which, if it's not already failing the build, it will if you move the `.Translations` into the single template.

I suspect that the cleanest, working solution we will find without doing too much work is to expand on the patch we added a few days ago: Make sure that the lazy content provider is triggered on all access to `cp` (including `RenderString`).

Comment (ptgott) [reply hugolib/page.go:406]: Thanks for the feedback. Would you mind explaining the data race a bit more? Which goroutines, processes, I/O, etc. would be racing?

I'll spend some time early this week implementing the approach you've suggested.

Comment (bep) [reply hugolib/page.go:406]: 1. We render pages in parallel.
2. Given the below, `AllTranslations` may be called from multiple go routines.
3. Any of the code lines reading or writing mutable page state below will be a potential data race (e.g. `if tp.pageOutput.cp == nil` and `tp.initContentProvider(cp)`). Go's race detector will fail the tests when run with `go test -race` (which we do on the CI server), but I guess you need to have test cases that trigger it.

```go
func (p *pageState) AllTranslations() page.Pages {
	p.s.h.init.translations.Do()

	// Hugo attempts to reuse content providers while preparing each page for
	// rendering. This approach means that sometimes, content providers for
	// translations are not initialized. If needed, initialize them here.
	for _, tr := range p.allTranslations {
		tp, ok := tr.(*pageState)
		if !ok {
			continue
		}
		if tp.pageOutput.cp == nil {
			cp, err := newPageContentOutput(tp, tp.pageOutput)
			if err != nil {
				// This will be caught by texttemplate.safeCall
				panic(fmt.Errorf("error rendering page translation: %w", err))
			}
			tp.initContentProvider(cp)
		}
	}

	return p.allTranslations
}
```

**Comment by ptgott** [comment]
@bep I've suggested initializing a `LazyContentProvider` inside `RenderString`. If this approach looks okay, should I go ahead and see if other `*pageState` methods need a similar treatment?

File: hugolib/page.go [hunk 2]
```diff
@@ -635,7 +635,19 @@ func (p *pageState) RenderString(args ...interface{}) (template.HTML, error) {
 		}
 	}
 
-	c, err := p.pageOutput.cp.renderContentWithConverter(conv, []byte(s), false)
+	var cp *pageContentOutput
+
+	// If the current content provider is not yet initialized, do so now.
+	if lcp, ok := p.pageOutput.ContentProvider.(*page.LazyContentProvider); ok {
```
Comment (bep) [inline hugolib/page.go:641]: So, this is conceptually what we need, but I would love if we could do this in one place. I think that if we use the same "interface approach" for RenderString (and potentially others) and make LazyContentProvider implement that interface, that should work.

**Comment by bep** [comment]
I have some time today and will look closer at this PR -- again, much appreciated.

**Comment by bep** [comment]
@ptgott I have added a commit to your PR which is a little bit more elaborate, but it's just moving the `RenderString` and `Render` code down to where it belongs, I guess. Note that there may still be cases where `.Translations[0].SomeMethod` may still return empty (I have always thought about the translation listings as mostly informative/metadata), but at least now it's not clearly specificed by an interface.
