### PR TITLE
exif: Allow more spacing characters in strings

### LINKED ISSUE #8079: Image descriptions in EXIF data with non ASCII characters is missing
### What version of Hugo are you using (`hugo version`)?

Hugo Static Site Generator v0.79.1/extended darwin/amd64 BuildDate: unknown
(Installed using homebrew)

### Does this issue reproduce with the latest release?
Yes

### Description 
I'm using Hugo to build a photo gallery website, and using the data in the `imagedescription` tag in the EXIF data to display a description below the image. I have noticed that images with non ASCII characters in the field have this element missing in the EXIF object. 

### Steps to reproduce
Use the `Exif.Tags.ImageDescription` to display the image description in a template with a description like this:

> Città del Vaticano #vatican #vaticancity

Observe that the `Exif.Tags.ImageDescription` variable is empty

Use the same template with an image description like this:

> Citta del Vaticano #vatican #vaticancity

Observe that the `Exif.Tags.ImageDescription` variable contains the description from the image. 

Other characters that I've seen that cause this issue are:

`“` instead of `"` or `‘` instead of `'` or any emoji character

### Additional information

The EXIF tags are being written with version 12 of [exiftool](https://exiftool.org/)

### PR DESCRIPTION
**Pull request by moorereason**
The root cause of issue #8079 was a non-breaking space (U+0160).
`unicode.IsPrint` only allows the ASCII space (U+0020).  Be more lenient
by using `unicode.IsGraphic` instead.

Fixes #8079

### CODE REVIEW

**Comment by bep** [comment]
Can you fix the commit message?

**Comment by moorereason** [comment]
Fixed.

File: resources/images/exif/exif.go [hunk 1]
```diff
@@ -227,7 +227,7 @@ func (e *exifWalker) Walk(f _exif.FieldName, tag *tiff.Tag) error {
 func nullString(in []byte) string {
 	var rv bytes.Buffer
 	for _, b := range in {
-		if unicode.IsPrint(rune(b)) {
+		if unicode.IsGraphic(rune(b)) {
```
Comment (bep) [inline resources/images/exif/exif.go:230]: OK, taking a second look at this, there is one more error in this, as this will not handle multi-byte runes. See the loop in this example:

https://golang.org/pkg/unicode/utf8/#DecodeRune

**Review by bep — CHANGES_REQUESTED** [review]

File: resources/images/exif/exif.go (hunk 1 above)
Comment (moorereason) [reply resources/images/exif/exif.go]: Commit pushed.  Fixing this should remove the need for the `utf8.ValidString` check.  PTAL
