### PR TITLE
common: Fix elements are doubling when append a not assignable type

### LINKED ISSUE #6188: Doubling of last slice element when adding template.HTML
I came across a weird error that I could boil down to this minimal example:

```
{{ $c := delimit (slice "c") " " }}<!-- should be 'c' -->
{{ $abc_slice := slice "a" | append "b" $c  }}<!-- should be ['a','b','c'] -->
{{ $abc := delimit $abc_slice "+" }}<!-- should be 'a+b+c' -->
{{ errorf "'%s' (%T) - '%s' (%T)" $c $c $abc $abc }}
```

Put that in a shortcode and strangely enough, the result is:

`'c' (template.HTML) - 'a+b+b+c' (template.HTML)`

As you can see, b is doubled.

The problem goes away if you add ` | print` to $c, making it a string. I wonder why it's not a string in the first place.

Thanks in advance for any comments and fixing.

### PR DESCRIPTION
**Pull request by vazrupe**
Fixes #6188

### CODE REVIEW

File: tpl/collections/collections.go [hunk 1]
```diff
@@ -84,9 +83,9 @@ func (ns *Namespace) After(index interface{}, seq interface{}) (interface{}, err
 	return seqv.Slice(indexv, seqv.Len()).Interface(), nil
 }
 
-// Delimit takes a given sequence and returns a delimited HTML string.
+// Delimit takes a given sequence and returns a delimited string.
 // If last is passed to the function, it will be used as the final delimiter.
-func (ns *Namespace) Delimit(seq, delimiter interface{}, last ...interface{}) (template.HTML, error) {
+func (ns *Namespace) Delimit(seq, delimiter interface{}, last ...interface{}) (string, error) {
```
Comment (bep) [inline tpl/collections/collections.go]: Can you revert this change. It's not directly relevant to the issue in question, and it may also be a possibly breaking change.

**Comment by vazrupe** [comment]
@bep 

Okay. I will split the patch.

**Comment by bep** [comment]
Thanks for this!
