### PR TITLE
markup/asciidocext: Fix AsciiDoc TOC with code

### LINKED ISSUE #7649: AsciiDoc TableOfContents doesn't handle `code` properly
When a title in AsciiDoc contains `` `inlined code` ``, it doesn't appear in the table of contents and multiple entries are created with the text surrounding it.

For example, this AsciiDoc:
```
== Some `code` in the title
```

Will generate a TOC with two entries pointing to the same place:

* Some
* in the title

(This is handled correctly in Markdown.)

### PR DESCRIPTION
**Pull request by helfper**
Running this adoc (https://asciidoctor.org/docs/install-toolchain/) through Hugo with Hugo Learn Theme, currently produces:

old_toc

With this PR:

new_toc

Fixes #7649

### CODE REVIEW

File: markup/tableofcontents/tableofcontents.go [hunk 1]
```diff
@@ -40,19 +40,19 @@ type Root struct {
 }
 
 // AddAt adds the header into the given location.
-func (toc *Root) AddAt(h Header, y, x int) {
-	for i := len(toc.Headers); i <= y; i++ {
+func (toc *Root) AddAt(h Header, row, level int) {
```
Comment (bep) [inline markup/tableofcontents/tableofcontents.go:43]: This does not look related.

**Review by bep — CHANGES_REQUESTED** [review]

File: markup/tableofcontents/tableofcontents.go (hunk 1 above)
Comment (helfper) [reply markup/tableofcontents/tableofcontents.go:43]: It's only related in the sense that it's called in
https://github.com/gohugoio/hugo/blob/64fcb35c13829bdc50d0f92628cc60674ed5a193/markup/asciidocext/convert.go#L276-L279

And I had to read it to understand how the ToC works in Hugo. Parameters named `y` and `x` didn't help with that.

I'm happy to revert this change in this PR if you prefer, but I think you should consider adding it in a future commit as it helps with the readability and it's consistent with the variable names used in the only other place it's called:
https://github.com/gohugoio/hugo/blob/64fcb35c13829bdc50d0f92628cc60674ed5a193/markup/goldmark/toc.go#L58
