### PR TITLE
internal/warpc: Increase WebP memory limit to 256 MiB

### LINKED ISSUE #14282: WebPEncode failed: 1 (OUT_OF_MEMORY: Out of memory allocating objects)
Hi

On the newest release from today, `v0.153.0`, I get this error:

```
Start building sites …
hugo v0.153.0-b4128babb839feaa962c00e777f0d2fe8d811f7d+extended linux/amd64 BuildDate=2025-12-19T10:14:01Z VendorInfo=gohugoio

WebPEncode failed: 1 (OUT_OF_MEMORY: Out of memory allocating objects)
WebPEncode failed: 1 (OUT_OF_MEMORY: Out of memory allocating objects)
WebPEncode failed: 1 (OUT_OF_MEMORY: Out of memory allocating objects)
WebPEncode failed: 1 (OUT_OF_MEMORY: Out of memory allocating objects)
WebPEncode failed: 1 (OUT_OF_MEMORY: Out of memory allocating objects)
Built in 9568 ms
ERROR error building site: render: [en v1.0.0 guest] failed to render pages: render of ...
```

This is the relevant snippet of code which converts my images into the WebP format:

```
{{ $img := .Page.Resources.GetMatch (.Get "src") }}
{{ if not (strings.HasSuffix $img.Name "gif") }}
{{ $img := $img.Process "webp picture q90" }}
{{ end }}

...
{{ $img.RelPermalink }}
---
```

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.153.0-b4128babb839feaa962c00e777f0d2fe8d811f7d+extended linux/amd64 BuildDate=2025-12-19T10:14:01Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes and **only** on the latest release.

### PR DESCRIPTION
**Pull request by jmooring**
Closes #14282

### CODE REVIEW

**Comment by jmooring** [comment]
This reduces the pool size from 2 to 1, and increases the memory  limit from 32 MiB to 256 MiB (4096 MiB is the max allowed).

When set to 64 MiB we can process the file from #14282.
When set to 128 MiB we can process a file that is ~ 4 MB.
When set to 256 MiB we can process a file that is ~ 7 MB.

This test repo processes the original image from #14282, plus 3 other images ranging from 1.3 MB to 7 MB:

```text
git clone --single-branch -b hugo-github-issue-14282 https://github.com/jmooring/hugo-testing hugo-github-issue-14282
cd hugo-github-issue-14282
hugo
```

File: internal/warpc/warpc.go [hunk 1]
```diff
@@ -575,8 +575,8 @@ func newDispatcher[Q, R any](opts Options) (*dispatcherPool[Q, R], error) {
 	}
 
 	if opts.Memory <= 0 {
-		// 32 MiB
-		opts.Memory = 32
+		// 256 MiB (4096 MiB Max)
+		opts.Memory = 256
```
Comment (bep) [inline internal/warpc/warpc.go]: This needs to be set on the webp options (where you set PoolSize: 1 above). This default is also used for Katex, which does not need this much memory.

Comment (bep) [reply internal/warpc/warpc.go]: I will fix it ...

**Comment by bep** [comment]
OK; lets keep it at 256 (I'm assuming Wazero is clever enough to not use all of it if it doesn't need to...) but your test case was not very unrealistic:

```handlebars
{{ with .Process "webp" }}
{{ end }}
```

If you change that to this it runs fine with 64 MiB limit:

```handlebars
{{ with .Resize "webp 1980x1080" }}
{{ end }}
```
