### PR TITLE
config/allconfig: Throw error when output format is not defined

### LINKED ISSUE #13199: config/allconfig: Error not thrown when output format is not defined
Reference: <https://discourse.gohugo.io/t/seems-hugo-no-longer-throw-an-error-if-output-format-is-invalid/52912>

This worked as expected through v0.122.0. Failing test:

```go
// Issue 13199
func TestInvalidOutputFormat(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
disableKinds = ['page','rss','section','sitemap','taxonomy','term']
[outputs]
home = ['html','foo']
-- layouts/index.html --
x
`

	b, err := hugolib.TestE(t, files)
	b.Assert(err.Error(), qt.Contains, `failed to create config: unknown output format "foo" for kind "home"`)
}
```

### PR DESCRIPTION
**Pull request by jmooring**
Fixes #13199

### CODE REVIEW

File: config/allconfig/allconfig.go [hunk 1]
```diff
@@ -734,7 +734,7 @@ func (c *Configs) Validate(logger loggers.Logger) error {
 
 // transientErr returns the last transient error found during config compilation.
 func (c *Configs) transientErr() error {
-	for _, l := range c.LanguageConfigSlice {
```
Comment (jmooring) [inline config/allconfig/allconfig.go:737]: `(allconfig.Configs).LanguageConfigSlice` is empty at this point. It is populated by `(allconfig.Configs).Init` which isn't called until _after_ we've checked for transient errors.
