### PR TITLE
Filter dot files etc. in i18n

### LINKED ISSUE #11993: Dot file in i18n directory throws error
```text
i18n/
├── .gitkeep
├── de.toml
└── en.toml
```

> Error: error building site: "art-x-": language: tag is not well-formed

No error with v0.122.0. Found this building site from a recent forum topic.

### PR DESCRIPTION
**Pull request by bep**
Closes #11993

### CODE REVIEW

**Review by Lule8885 — COMMENTED** [review]
Uhhj

File: hugolib/language_test.go [hunk 1]
```diff
@@ -135,3 +135,14 @@ FormatNumberCustom: 12,345.68
...
+// Issue 11993.
+func TestI18nDotFile(t *testing.T) {
+	files := `
+-- hugo.toml --{}
+baseURL = "https://example.com"
+-- i18n/.keep --
+-- data/.keep --
+`
+	Test(t, files)
+}
```
Comment (Lule8885) [inline hugolib/language_test.go:148]: []()@Lule8885

**Review by Lule8885 — COMMENTED** [review]
To see
