### PR TITLE
resources/resource: Fix GroupByParamDate with raw TOML dates

### LINKED ISSUE #11563: With unquoted TOML values, GroupByParamDate requires fully qualified date
The unexpected behavior is limited to unquoted TOML values.

`GroupByParamDate "eventDate" "2006-01"`works fine with all of these:

```text
title = 'something'
eventDate = 2022-08-13T13:57:43-07:00   # unquoted 
```

```text
title = 'something'
eventDate = '2022-08-13T13:57:43-07:00'   # quoted 
```

```text
title = 'something'
eventDate = '2022-08-13'  # quoted 
```

But pages with this parameter date format are not grouped:

```text
title = 'something'
eventDate = 2022-08-13  # unquoted 
```

`GroupByDate`, `GroupByExpiryDate`, `GroupByLastmod`, and `GroupByPublishDate` work fine any of the four date values.

In that unquoted TOML dates are the best choice[^1] for custom date params, this seems like something we should fix.

---

Reproducible example:

```text
git clone --single-branch -b hugo-github-issue-11563 https://github.com/jmooring/hugo-testing hugo-github-issue-11563
cd hugo-github-issue-11563
hugo server
```

[^1]: With unquoted TOML dates you can do `time.Time` comparisons wit the `where` function.

### PR DESCRIPTION
**Pull request by jmooring**
Closes #11563

### CODE REVIEW

File: resources/resource/resource_helpers.go [hunk 1]
```diff
@@ -55,6 +58,11 @@ func getParam(r Resource, key string, stringToLower bool) any {
 		return cast.ToFloat64(v)
 	case time.Time:
 		return val
+	case toml.LocalDate, toml.LocalDateTime:
+		if vt, ok := hreflect.AsTime(reflect.ValueOf(val), time.UTC); ok {
```
Comment (bep) [inline resources/resource/resource_helpers.go:62]: Using reflect here isn't needed. You can just do `val.AsTime(time.UTC)`.

Comment (jmooring) [reply resources/resource/resource_helpers.go]: I couldn't quite figure out how to do what you describe, but hopefully using `htime.ToTimeInDefaultLocationE(val, time.UTC)` is sufficient.

File: resources/resource/resource_helpers.go [hunk 2]
```diff
@@ -55,6 +57,12 @@ func getParam(r Resource, key string, stringToLower bool) any {
 		return cast.ToFloat64(v)
 	case time.Time:
 		return val
+	case toml.LocalDate, toml.LocalDateTime:
+		val, err := htime.ToTimeInDefaultLocationE(val, time.UTC)
```
Comment (bep) [inline resources/resource/resource_helpers.go:61]: This is nit picking, but but when you have a known type, converting it to another type (e.g. `interface{}` or `reflect.Value`) just so it can be converted back to the type you started with. I don't think it allocates any extra memory in this particular case, but I had to navigate into the ToTime... func to see what it does. I suggest you just call val.AsTime directly.

Comment (jmooring) [reply resources/resource/resource_helpers.go]: Sorry about the iterations here. This was the self-inflicted wound:
```
case toml.LocalDate, toml.LocalDateTime:
```

<https://go.dev/ref/spec#Type_switches>

> In clauses with a case listing exactly one type, the variable has that type; otherwise, the variable has the type of the expression in the TypeSwitchGuard.

Which meant I had type `any` instead of the toml.Whatever type, which meant AsTime() was not an option. Split the case; all is good.
