### PR TITLE
shortcode: Catch incomplete shortcode error

### LINKED ISSUE #6866: Incomplete shortcodes crash hugo running in serve mode.
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

Hugo Static Site Generator v0.64.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

---

I think this is likely the same as https://github.com/gohugoio/hugo/issues/6857

Steps to reproduce:

(Mac)
Run Visual Studio Code with auto-save enabled (set at 250ms).
Run `hugo serve -D -F`

If you type 

```{{< >}}```

or something that can be parsed as a shortcode, but isn't yet valid, hugo seems to produce the stack dump below.

Fix:  gracefully handle bad shortcodes, and just log an error rather than crash.

```
Source changed "/dev/mysite/mermaid.md": WRITE
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4b62b10]

goroutine 980 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc00220cb80, 0x4, 0x0, 0xc0027686e0, 0x1, 0x1, 0x5554460)
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/shortcode.go:499 +0x550
github.com/gohugoio/hugo/hugolib.(*pageState).mapContent(0xc002734f30, 0xc00259c2a0, 0xc002268280, 0x0, 0xc000588b38)
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/page.go:738 +0xb16
github.com/gohugoio/hugo/hugolib.newPageWithContent.func1(0xc00259c2a0, 0x402f84a, 0xc000588b90)
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/page__new.go:233 +0x4b
github.com/gohugoio/hugo/hugolib.(*pagesMap).initPageMeta.func1()
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/pages_map.go:77 +0x50
sync.(*Once).doSlow(0xc000030020, 0xc000588c08)
        /usr/local/Cellar/go/1.13.7/libexec/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/Cellar/go/1.13.7/libexec/src/sync/once.go:57
github.com/gohugoio/hugo/hugolib.(*pagesMap).initPageMeta(0xc002768530, 0xc002734f30, 0xc00259c2a0, 0x58e463a, 0x4)
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/pages_map.go:75 +0xa1
github.com/gohugoio/hugo/hugolib.(*pagesMap).initPageMetaFor(0xc002768530, 0xc0023fc156, 0x6, 0xc00259c2a0, 0x0, 0xc00271e1d0)
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/pages_map.go:95 +0x429
github.com/gohugoio/hugo/hugolib.(*pagesMap).assemblePageMeta.func1(0xc0023fc156, 0x6, 0x56cb480, 0xc00259c2a0, 0xc00259c1c0)
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/pages_map.go:199 +0x66
github.com/armon/go-radix.recursiveWalk(0xc002735320, 0xc00057fea0, 0x56cb480)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc002735410, 0xc00057fea0, 0x56cb400)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc002735140, 0xc00057fea0, 0xc0007ef110)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc002735050, 0xc00057fea0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).Walk(...)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pagesMap).assemblePageMeta(0xc002768530, 0xc0003f0a80, 0x0)
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/pages_map.go:196 +0x6c
github.com/gohugoio/hugo/hugolib.(*HugoSites).assemble.func1(0x0, 0x0)
        /private/tmp/hugo-20200204-77776-1t93oty/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/hugo_sites_build.go:266 +0xff
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc002734ff0, 0xc002735020)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

### PR DESCRIPTION
**Pull request by satotake**
Currently, no name shortcodes (`{{< >}}`) enter unexpected branch and
throw `BUG: template info not set`. This patch checks if shortcode has
name or not earlier and throws specific error.

In addition,
- Add test case
- Modify `CheckShortCodeMatchAndError` a little to assert the error

Closes #6866

### CODE REVIEW

File: hugolib/shortcode.go [hunk 1]
```diff
@@ -460,6 +458,10 @@ Loop:
 		switch {
 		case currItem.IsLeftShortcodeDelim():
 			next := pt.Peek()
+			if next.IsRightShortcodeDelim() {
+				// no name: {{< >}} or {{% %}}
+				return sc, errors.New("Shortcode has no name")
```
Comment (bep) [inline hugolib/shortcode.go:463]: Go errors should start with lowercase; we probably don't do that everywhere, but I see all the errors in this file does, so we might as well be lenient about this.

**Review by bep — CHANGES_REQUESTED** [review]

File: hugolib/shortcode.go (hunk 1 above)
Comment (satotake) [reply hugolib/shortcode.go]: Thanks. I will be careful from now on
